using AutoMapper;
using PublicCommon.Common;

namespace MyTown.SharedModels.DTOs;

public class CardBrandDto : IEquatable<CardBrandDto> //: TownCardBrand
    {
    public CardBrandDto()
        {
        Image1 = new ImageInfoBase64Url();
        Image2 = new ImageInfoBase64Url();
        }
    //public const string keyword = "BI";
    //public string FileName(string? actualName) => $"{keyword}_{IdCardBrand}_{actualName ?? ""}";
    //public void FileNamesUpdate()
    //    {
    //    if (ImageInfoBase64Url.IsBase64(Image1)) Image1.FileName = FileName(Image1.FileName);
    //    if (ImageInfoBase64Url.IsBase64(Image2)) Image2.FileName = FileName(Image2.FileName);
    //    }

    //public List<ImageInfo> ToUploadImages()
    //    {
    //    List<ImageInfo> list = new List<ImageInfo>();
    //    FileNamesUpdate();
    //    if (ImageInfoBase64Url.IsBase64(Image1)) list.Add(new ImageInfo(Image1, nameof(Image1)));
    //    if (ImageInfoBase64Url.IsBase64(Image2)) list.Add(new ImageInfo(Image2, nameof(Image2)));
    //    return list;
    //    }
    //public (List<ImageInfo> listToUpload, List<ImageInfo> listToDelete) GetUploadAndDeleteImages(CardBrand? existing)
    //    {
    //    List<ImageInfo> listToUpload = new List<ImageInfo>();
    //    List<ImageInfo> listToDelete = new List<ImageInfo>();
    //    FileNamesUpdate();
    //    ImageInfoBase64Url.LoadUploadDelete(Image1, nameof(Image1), existing?.Image1, listToUpload, listToDelete);
    //    ImageInfoBase64Url.LoadUploadDelete(Image2, nameof(Image2), existing?.Image2, listToUpload, listToDelete);
    //    return new(listToUpload, listToDelete);
    //    }

    public int IdCardBrand { get; set; }
    //here Id is cardId only ,not autogenerated
    public ImageInfoBase64Url? Image1 { get; set; } = new();

    public ImageInfoBase64Url? Image2 { get; set; } = new();

    // public new TownCardDto? ApprovedCard { get; set; } = new();

    //checks either it contains base64 valid or url valid
    public static bool IsNullOrDefault(CardBrandDto? brand) => (brand == null ||
        (ImageInfoBase64Url.IsNullOrDefault(brand.Image1) && ImageInfoBase64Url.IsNullOrDefault(brand.Image2)));
    public static bool IsNewBase64Valid(CardBrandDto? brand)
        => IsNullOrDefault(brand) ? false :
        ImageInfoBase64Url.IsBase64(brand?.Image1) || ImageInfoBase64Url.IsBase64(brand?.Image2);


    public void ResetImages()
        {
        Image1 = null;
        Image2 = null;
        }

    //IEquatable<CardProduct> implementation
    public bool Equals(CardBrandDto? otherBrand)//compares including id
        {//usage bool isEqual1 = person1.Equals(person2);
        if (otherBrand == null) return false; // Not the same type
        return IdCardBrand == otherBrand.IdCardBrand && EqualImages(otherBrand); // Compare properties
        }

    public bool EqualImages(CardBrandDto? otherBrand)//compares without id
        {//usage bool isEqual1 = person1.EqualImages(person2);
        if (otherBrand == null) return false; // Not the same type

        //IdCardBrand == otherCard.IdCardBrand //here wont check for id
        return Image1 == otherBrand.Image1 && Image2 == otherBrand.Image2; // Compare properties
        }

    public bool EqualImages(CardBrand? otherBrand)//compares without id
        {//usage bool isEqual1 = person1.EqualImages(person2);
        if (otherBrand == null) return false; // Not the same type

        //IdCardBrand == otherCard.IdCardBrand //here wont check for id
        return ImageInfoBase64Url.Equals(Image1, otherBrand.Image1) && ImageInfoBase64Url.Equals(Image2, otherBrand.Image2); // Compare properties
        }


    private class Mapping : Profile
        {
        public Mapping()
            {
            CreateMap<CardBrand, CardBrandDto>()
                 .ForMember(d => d.Image1, opt => opt.MapFrom(src => new ImageInfoBase64Url(src.Image1)))
                 .ForMember(d => d.Image2, opt => opt.MapFrom(src => new ImageInfoBase64Url(src.Image2)))
            // .ForMember(d => d.ApprovedCard, opt => opt.MapFrom(imageValue => imageValue.ApprovedCard))
            .ReverseMap();

            CreateMap<CardBrandDto, CardBrand>()
                 .ForMember(d => d.Image1, opt => opt.MapFrom(src => ImageInfoBase64Url.GetUrl(src.Image1)))
                 .ForMember(d => d.Image2, opt => opt.MapFrom(src => ImageInfoBase64Url.GetUrl(src.Image2)))
            // .ForMember(d => d.ApprovedCard, opt => opt.MapFrom(imageValue => imageValue.ApprovedCard))
            .ReverseMap();
            }
        }
    }
